name: flake-update
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 10 * * *' 

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: update
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          pr-title: "Update flake.lock"
          pr-assignees: rubikcubed
